# Generated by Django 6.0.4 on 2026-04-14 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto')], max_length=10)),
                ('category', models.CharField(choices=[('sueldo', 'Sueldo'), ('alquiler', 'Alquiler'), ('comida', 'Comida'), ('transporte', 'Transporte'), ('entretenimiento', 'Entretenimiento'), ('servicios', 'Servicios'), ('inversion', 'Inversión'), ('ahorro', 'Ahorro'), ('otro', 'Otro')], max_length=50)),
                ('instrument_type', models.CharField(choices=[('pesos', 'Pesos'), ('dolar_oficial', 'Dólar Oficial'), ('dolar_blue', 'Dólar Blue'), ('plazo_fijo_uva', 'Plazo Fijo UVA'), ('bitcoin', 'Bitcoin')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='transaction_user_id_dff1f0_idx'), models.Index(fields=['user', 'category'], name='transaction_user_id_cfabf3_idx'), models.Index(fields=['user', 'instrument_type'], name='transaction_user_id_a1eb2d_idx')],
            },
        ),
    ]
