# Generated by Django 6.0.4 on 2026-04-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_bitcoin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del Bitcoin (ARS) al momento de la transacción', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_dollar_blue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cotización del dólar blue al momento de la transacción', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_uva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor UVA al momento de la transacción', max_digits=15, null=True),
        ),
    ]
