# Generated by Django 6.0.4 on 2026-04-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_exchange_rate_bitcoin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_dolar_oficial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cotización del dólar oficial al momento de la transacción', max_digits=15, null=True),
        ),
    ]
